file_format: "1"
id: auryl
name: Auryl
type: shield
url: https://github.com/genkobar/auryl/
requires: [pro_micro]
features:
  - keys
  - encoder
  # - trackball
siblings:
  - auryl_left
  - auryl_right