manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: genkobar
      url-base: https://github.com/genkobar
    - name: cdc
      url-base: https://github.com/cdc-mkb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: a8c7cf4f19ad80eb8e6148f872d3a9584b25befc
      import: app/west.yml
  self:
    path: config
