manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: genkobar
      url-base: https://github.com/genkobar
    - name: cdc
      url-base: https://github.com/cdc-mkb
    - name: w84miracle
      url-base: https://github.com/w84miracle
    - name: genkobar
      url-base: https://github.com/genkobar
  projects:
    - name: zmk
      remote: genkobar
      revision: split-encoder
      import: app/west.yml
  self:
    path: config
